### ISSUE TITLE
Hello, do you have any plan to release all the code, such as the training code? Your work is very good, thank you！

### ISSUE THREAD

**Issue by LiHaoHN** [hamzapehlivan/StyleRes#1]

**Comment by hamzapehlivan** [comment]
Hello, 

Thank you for your interest in our paper!

I will release the inference and evaluation codes as soon as possible. After I am done with these, I can release the training code. 

I am adding it to To-Do list

**Comment by LiHaoHN** [comment]
Got it! Thank you a lot, again.
