### ISSUE TITLE
training code

### ISSUE THREAD

**Issue by FST-ZHUSHUMIN** [hamzapehlivan/StyleRes#2]
Dear author, as the title, please release the training code. Thank you!

**Comment by sunzhe09** [comment]
me too

**Comment by taluos** [comment]
me too !

**Comment by hamzapehlivan** [comment]
Training code emailed upon request

**Comment by phuongpropk05** [comment]
Dear author, can you emailed me the training code too. My email is hoangphuong070501@gmail.com. Thank you!

**Comment by hwd-code** [comment]
Can I get one copy training code,i don't have gmail,just QQ email:2448408536@qq.com
