### ISSUE TITLE
Integrating custom trained stylegan model with styleres

### ISSUE THREAD

**Issue by waleedrazakhan92** [hamzapehlivan/StyleRes#5]
I was wondering if the current StyleRes model is compatible with a StyleGan model that is not trained no a FFHQ dataset. I have a around 50,000 aligned and cropped images which are not from the FFHQ dataset and I wanted to use the latents that are output from the StyleRes model to manipulate the images. But I want to integrate my trained weights with the styleres. How do i integrate my model so that the inversion quality remains the same?
The problem I'm facing is that when i put the latent vector from the styleres into my generator, the reproduced image is not the same as the one that would be produced from the original ffhq model.

**Comment by hamzapehlivan** [comment]
Hello, 
If the distributions are different than each other (StyleGAN model trained with FFHQ, but you have a car dataset), then it will not work at all. However, if the distributions are closer I expect it to work. 

Note that the StyleGAN we used is trained with FFHQ, but the results given in the paper are coming from CelebAHQ dataset. This means we are already certain that this model works under similar distribution setting. 

Hope this helps

**Comment by waleedrazakhan92** [comment]
Thankyou so much for the response. My dataset is also facial data like FFHQ but i've made them a lot cleaner by removing the partial faces appearing in the images and people wearing jewelry. So yes the data is from similar distribution.
